services:
  #db
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # node api
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      DB_CONN_STRING: mongodb://mongo_db:27017
      DB_NAME: reverseAuctionDB
      COLLECTION_NAME: reverseAuctionCollection
      NAME: reverseAuctionApi
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
